---
title: "Assignment 1: Introduction"
author: "Tani Valdez Rivas"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assigment section on Sakai.


## 1) Finish setting up R Studio

### Install TinyTex
Now, run this code cell the same way. This will install "tinytex" -- a helper app that allows you to knit your markdown documents into professional quality PDFs.
```{r install tiny tex, eval=FALSE, include=FALSE}
#install tinytext
tinytex::install_tinytex()
```

### Set your default knit directory
This setting will help deal with relative paths later on...
 - From the Tool menu, select `Global Options`
 - Select the RMarkdown section
 - In the "Evaluate chunks in directory", set the option to "Project" (If you don't see this option, try restarting RStudio.)


## 2) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: I have little to no experience with Git and R. In my undergraduate courses, we have previously used Git to create and edit websites, but I did not learn how to analyze data through various applications. I have worked and cleaned large data sets so I am not privy on how to search and analyze data.

2. Are there any components of the course about which you feel confident?

> Answer: The only componenet I feel somewhat comfortable is Python. I have used python for my observational and data anlysis in marine physics undergraduate course to write scripts. Through these scripts, we created and modified graphs of timeseries that looked at SST for a duration of time. While I had some assitance from AI, I better understood why some commands had to be used.

3. Are there any components of the course about which you feel apprehensive?

> Answer: In total honesty, the rest of my course makes me feel wary. For assignment one: task 2, I was confused if I needed to download the .rmd file in my Git repository or on R. Being this is my first time using R, my brain is slightly struggling on the pull and push components of R. As I look through the syallbus, I feel hesitant on some of the topics as I have primarily used exccel. But, as I keep exploring R and try to figure out some the commands and tools, I'm slowly feeling more sure of myself.  test 


## 3) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: https://github.com/Tani-ValdezRivas/EDE_Fall2023

## 4) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Sakai. 
